# Site settings
title: Lars Ã˜rnlo
email: lars.oernlo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello there, and welcome to my website.
  My interests mostly include development, system administration, video games, and food.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: ypperlig
github_username:  ypperlig

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 1 # amount of posts to show
paginate_path: /page:num/